version: '3'
services:
  back-end:
    depends_on:
      - mysqldb
    build: ./back-end
    container_name: back-end
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    
  mysqldb:
    image: mysql
    container_name: mysql-cash-book
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql:/var/lib/mysql
      - ./back-end/cash_book_db.sql:/docker-entrypoint-initdb.d/cash_book_db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin-cash-book
    ports:
      - $PHPMYADMIN_LOCAL_PORT:$PHPMYADMIN_DOCKER_PORT 
    environment: 
      - PMA_ARBITRARY:1
      - PMA_HOST=mysqldb 
      - MYSQL_USERNAME=$PHPMYADMIN_USER
      - MYSQL_ROOT_PASSWORD=$PHPMYADMIN_PASSWORD
      
volumes: 
  mysql: